# Site Config

name: AlexFlipnote
title: AlexFlipnote

themecolour: "#2196F3"

domain: "https://alexflipnote.xyz"
baseurl: ""
url: "https://alexflipnote.xyz"
encoding: utf-8

include: ['_pages', '_docs']

plugins:
  - jekyll-seo-tag

twitter:
  username: AlexFlipnote

sass:
  sass_dir: _sass
  style: compressed
